import { getDatabase } from '../connection';
import { EmojiAction } from '../models';
import {
  EmotionEffect,
  MetabolismVector,
} from '../../types/emoji';
import { createLogger } from '../../utils/logger';

const log = createLogger('[EmojiActionRepo]');

function mapRowToAction(row: any): EmojiAction {
  return {
    id: row.id,
    entityId: row.entity_id,
    emojiNative: row.emoji_native,
    emotionEffect: row.emotion_effect ? JSON.parse(row.emotion_effect) : null,
    metabolismVector: row.metabolism_vector ? JSON.parse(row.metabolism_vector) : null,
    substitutionText: row.substitution_text,
    autoGenerated: row.auto_generated === 1,
    isDefault: row.is_default === 1,
    createdAt: new Date(row.created_at),
    updatedAt: new Date(row.updated_at),
  };
}

/** WHERE clause fragment to exclude soft-deleted rows */
const NOT_DELETED = 'deleted_at IS NULL';

export async function getEmojiActionsForEntity(
  entityId: string,
): Promise<Map<string, EmojiAction>> {
  const db = getDatabase();
  const [result] = await db.executeSql(
    `SELECT * FROM entity_emoji_actions WHERE entity_id = ? AND ${NOT_DELETED} ORDER BY emoji_native`,
    [entityId],
  );

  const map = new Map<string, EmojiAction>();
  for (let i = 0; i < result.rows.length; i++) {
    const action = mapRowToAction(result.rows.item(i));
    map.set(action.emojiNative, action);
  }
  return map;
}

export async function getEmojiAction(
  entityId: string,
  emojiNative: string,
): Promise<EmojiAction | null> {
  const db = getDatabase();
  const [result] = await db.executeSql(
    `SELECT * FROM entity_emoji_actions WHERE entity_id = ? AND emoji_native = ? AND ${NOT_DELETED}`,
    [entityId, emojiNative],
  );

  if (result.rows.length === 0) return null;
  return mapRowToAction(result.rows.item(0));
}

export async function getAllEmojiActionsArray(
  entityId: string,
): Promise<EmojiAction[]> {
  const db = getDatabase();
  const [result] = await db.executeSql(
    `SELECT * FROM entity_emoji_actions WHERE entity_id = ? AND ${NOT_DELETED} ORDER BY is_default DESC, emoji_native`,
    [entityId],
  );

  const actions: EmojiAction[] = [];
  for (let i = 0; i < result.rows.length; i++) {
    actions.push(mapRowToAction(result.rows.item(i)));
  }
  return actions;
}

export async function createEmojiAction(
  action: Omit<EmojiAction, 'createdAt' | 'updatedAt'>,
): Promise<void> {
  const db = getDatabase();
  const now = new Date().toISOString();

  await db.executeSql(
    `INSERT INTO entity_emoji_actions (
      id, entity_id, emoji_native, emotion_effect, metabolism_vector,
      substitution_text, auto_generated, is_default, deleted_at, created_at, updated_at
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, NULL, ?, ?)`,
    [
      action.id,
      action.entityId,
      action.emojiNative,
      action.emotionEffect ? JSON.stringify(action.emotionEffect) : null,
      action.metabolismVector ? JSON.stringify(action.metabolismVector) : null,
      action.substitutionText,
      action.autoGenerated ? 1 : 0,
      action.isDefault ? 1 : 0,
      now,
      now,
    ],
  );
}

export async function upsertEmojiAction(
  action: Omit<EmojiAction, 'createdAt' | 'updatedAt'>,
): Promise<void> {
  const db = getDatabase();
  const now = new Date().toISOString();

  await db.executeSql(
    `INSERT OR REPLACE INTO entity_emoji_actions (
      id, entity_id, emoji_native, emotion_effect, metabolism_vector,
      substitution_text, auto_generated, is_default, deleted_at, created_at, updated_at
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, NULL, ?, ?)`,
    [
      action.id,
      action.entityId,
      action.emojiNative,
      action.emotionEffect ? JSON.stringify(action.emotionEffect) : null,
      action.metabolismVector ? JSON.stringify(action.metabolismVector) : null,
      action.substitutionText,
      action.autoGenerated ? 1 : 0,
      action.isDefault ? 1 : 0,
      now,
      now,
    ],
  );
}

export async function deleteEmojiAction(actionId: string): Promise<void> {
  const db = getDatabase();
  const now = new Date().toISOString();
  await db.executeSql(
    'UPDATE entity_emoji_actions SET deleted_at = ?, updated_at = ? WHERE id = ?',
    [now, now, actionId],
  );
}

export async function deleteAllEmojiActions(entityId: string): Promise<void> {
  const db = getDatabase();
  const now = new Date().toISOString();
  await db.executeSql(
    'UPDATE entity_emoji_actions SET deleted_at = ?, updated_at = ? WHERE entity_id = ? AND deleted_at IS NULL',
    [now, now, entityId],
  );
}

export async function deleteDefaultEmojiActions(entityId: string): Promise<number> {
  const db = getDatabase();
  const now = new Date().toISOString();
  const [result] = await db.executeSql(
    'UPDATE entity_emoji_actions SET deleted_at = ?, updated_at = ? WHERE entity_id = ? AND is_default = 1 AND deleted_at IS NULL',
    [now, now, entityId],
  );
  return result.rowsAffected;
}

export async function countEmojiActions(entityId: string): Promise<number> {
  const db = getDatabase();
  const [result] = await db.executeSql(
    `SELECT COUNT(*) as count FROM entity_emoji_actions WHERE entity_id = ? AND ${NOT_DELETED}`,
    [entityId],
  );
  return result.rows.item(0).count;
}