/**
 * EmojiActionEditModal - Modal for creating/editing emoji actions
 */
import React, { useState, useEffect, useCallback } from 'react';
import {
  Modal,
  View,
  ScrollView,
  TouchableOpacity,
  TextInput,
  StyleSheet,
} from 'react-native';
import Icon from 'react-native-vector-icons/MaterialCommunityIcons';
import { ThemedText } from '../themed/ThemedText';
import { ThemedView } from '../themed/ThemedView';
import { EmojiPickerInline } from '../emoji/EmojiPickerInline';
import { EmojiText } from '../emoji/EmojiText';
import { EntityEmojiActionService } from '../../services/EntityEmojiActionService';
import { useAppTheme } from '../../contexts/ThemeContext';
import { EmojiAction } from '../../database/models';
import {
  EmojiEntry,
  EmotionEffect,
  MetabolismVector,
  Ekman8Emotion,
  EKMAN8_EMOTIONS,
} from '../../types/emoji';

interface EmojiActionEditModalProps {
  entityId: string;
  existingAction: EmojiAction | null; // null = creating new
  existingActions: EmojiAction[]; // for duplicate emoji check
  visible: boolean;
  onSave: (action: Omit<EmojiAction, 'createdAt' | 'updatedAt'>) => Promise<void>;
  onClose: () => void;
}

export const EmojiActionEditModal: React.FC<EmojiActionEditModalProps> = ({
  entityId,
  existingAction,
  existingActions,
  visible,
  onSave,
  onClose,
}) => {
  const { theme } = useAppTheme();
  const colors = theme?.colors;

  // Form state
  const [selectedEmoji, setSelectedEmoji] = useState<string>('');
  const [emotionEnabled, setEmotionEnabled] = useState(false);
  const [selectedEmotion, setSelectedEmotion] = useState<Ekman8Emotion>('joy');
  const [emotionDelta, setEmotionDelta] = useState('1.0');
  const [metabolismEnabled, setMetabolismEnabled] = useState(false);
  const [metabolismType, setMetabolismType] = useState<'eat' | 'drink' | 'sleep'>('eat');
  const [metabolismItem, setMetabolismItem] = useState('');
  const [substitutionText, setSubstitutionText] = useState('');

  // Emoji picker visibility
  const [showEmojiPicker, setShowEmojiPicker] = useState(false);

  // Initialize form when existing action is provided or modal opens
  useEffect(() => {
    if (existingAction) {
      setSelectedEmoji(existingAction.emojiNative);
      setSubstitutionText(existingAction.substitutionText || '');

      if (existingAction.emotionEffect) {
        setEmotionEnabled(true);
        setSelectedEmotion(existingAction.emotionEffect.emotion);
        setEmotionDelta(existingAction.emotionEffect.delta.toString());
      } else {
        setEmotionEnabled(false);
      }

      if (existingAction.metabolismVector) {
        setMetabolismEnabled(true);
        setMetabolismType(existingAction.metabolismVector.type as 'eat' | 'drink' | 'sleep');
        setMetabolismItem(existingAction.metabolismVector.item);
      } else {
        setMetabolismEnabled(false);
      }
    } else {
      // Reset for new action
      setSelectedEmoji('');
      setEmotionEnabled(false);
      setSelectedEmotion('joy');
      setEmotionDelta('1.0');
      setMetabolismEnabled(false);
      setMetabolismType('eat');
      setMetabolismItem('');
      setSubstitutionText('');
    }
  }, [existingAction, visible]);

  // Handle emoji selection
  const handleEmojiSelect = useCallback((emoji: EmojiEntry) => {
    setSelectedEmoji(emoji.native);
    setShowEmojiPicker(false);
  }, []);

  // Check for duplicate emoji
  const isDuplicateEmoji = useCallback(() => {
    if (!selectedEmoji) return false;
    return existingActions.some(
      (a) => a.emojiNative === selectedEmoji && a.id !== existingAction?.id
    );
  }, [selectedEmoji, existingActions, existingAction]);

  // Generate substitution text from current settings
  const handleAutoGenerate = useCallback(() => {
    const generated = EntityEmojiActionService.generateSubstitutionText({
      id: existingAction?.id || '',
      entityId,
      emojiNative: selectedEmoji,
      emotionEffect: emotionEnabled
        ? { emotion: selectedEmotion, delta: parseFloat(emotionDelta) || 0 }
        : null,
      metabolismVector: metabolismEnabled
        ? { type: metabolismType, item: metabolismItem || 'something' }
        : null,
      substitutionText: null,
      autoGenerated: true,
      isDefault: false,
      createdAt: existingAction?.createdAt ?? new Date(),
      updatedAt: existingAction?.updatedAt ?? new Date(),
    });
    setSubstitutionText(generated);
  }, [entityId, selectedEmoji, emotionEnabled, selectedEmotion, emotionDelta, metabolismEnabled, metabolismType, metabolismItem, existingAction]);

  // Handle save
  const handleSave = useCallback(async () => {
    if (!selectedEmoji) return;
    if (isDuplicateEmoji()) return;

    const emotionEffect: EmotionEffect | null = emotionEnabled
      ? { emotion: selectedEmotion, delta: parseFloat(emotionDelta) || 0 }
      : null;

    const metabolismVector: MetabolismVector | null = metabolismEnabled
      ? { type: metabolismType, item: metabolismItem || 'something' }
      : null;

    const action: Omit<EmojiAction, 'createdAt' | 'updatedAt'> = {
      id: existingAction?.id || `ea_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`,
      entityId,
      emojiNative: selectedEmoji,
      emotionEffect,
      metabolismVector,
      substitutionText: substitutionText || null,
      autoGenerated: false,
      isDefault: false,
    };

    await onSave(action);
  }, [
    selectedEmoji,
    isDuplicateEmoji,
    existingAction,
    entityId,
    emotionEnabled,
    selectedEmotion,
    emotionDelta,
    metabolismEnabled,
    metabolismType,
    metabolismItem,
    substitutionText,
    onSave,
  ]);

  if (!theme || !colors) return null;

  const duplicateError = isDuplicateEmoji();

  return (
    <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}>
      <View style={styles.overlay}>
        <ThemedView variant="elevated" style={[styles.container, showEmojiPicker && styles.containerExpanded]}>
          {/* Header */}
          <View style={[styles.header, { borderBottomColor: colors.border.default }]}>
            <TouchableOpacity onPress={onClose}>
              <Icon name="close" size={24} color={colors.text.primary} />
            </TouchableOpacity>
            <ThemedText weight="bold" size={18}>
              {existingAction ? 'Edit Action' : 'New Action'}
            </ThemedText>
            <TouchableOpacity
              onPress={handleSave}
              disabled={!selectedEmoji || duplicateError}
            >
              <ThemedText
                style={[
                  styles.saveButton,
                  {
                    color: !selectedEmoji || duplicateError
                      ? colors.text.disabled
                      : colors.accent.primary,
                  },
                ]}
              >
                Save
              </ThemedText>
            </TouchableOpacity>
          </View>

          {showEmojiPicker ? (
            /* Inline emoji picker — avoids nested Modal issues on Android */
            <View style={styles.inlinePickerContainer}>
              <View style={[styles.pickerToolbar, { borderBottomColor: colors.border.default }]}>
                <TouchableOpacity onPress={() => setShowEmojiPicker(false)}>
                  <Icon name="arrow-left" size={24} color={colors.text.primary} />
                </TouchableOpacity>
                <ThemedText weight="bold" size={16}>Select Emoji</ThemedText>
                <View style={{ width: 24 }} />
              </View>
              <EmojiPickerInline
                onEmojiSelected={handleEmojiSelect}
                theme={theme}
                containerStyle={{ maxHeight: undefined, flex: 1 }}
              />
            </View>
          ) : (
          <ScrollView style={styles.content}>
            {/* Emoji selector */}
            <View style={styles.section}>
              <ThemedText variant="secondary" size={12} style={styles.label}>
                EMOJI
              </ThemedText>
              <TouchableOpacity
                style={[
                  styles.emojiSelector,
                  {
                    backgroundColor: colors.background.base,
                    borderColor: duplicateError ? colors.status.error : colors.border.default,
                  },
                ]}
                onPress={() => setShowEmojiPicker(true)}
              >
                {selectedEmoji ? (
                  <EmojiText native={selectedEmoji} size={32} />
                ) : (
                  <ThemedText variant="muted">Select emoji...</ThemedText>
                )}
                <Icon name="chevron-down" size={20} color={colors.text.muted} />
              </TouchableOpacity>
              {duplicateError && (
                <ThemedText variant="muted" size={11} style={styles.errorText}>
                  This emoji is already used by another action
                </ThemedText>
              )}
            </View>

            {/* Emotion effect section */}
            <View style={styles.section}>
              <TouchableOpacity
                style={styles.toggleRow}
                onPress={() => setEmotionEnabled(!emotionEnabled)}
              >
                <View style={styles.toggleLeft}>
                  <Icon
                    name={emotionEnabled ? 'checkbox-marked' : 'checkbox-blank-outline'}
                    size={22}
                    color={colors.accent.primary}
                  />
                  <ThemedText style={styles.toggleLabel}>Emotion Effect</ThemedText>
                </View>
              </TouchableOpacity>

              {emotionEnabled && (
                <View style={styles.toggleContent}>
                  {/* Emotion chips */}
                  <View style={styles.chipContainer}>
                    {EKMAN8_EMOTIONS.map((emotion) => (
                      <TouchableOpacity
                        key={emotion}
                        style={[
                          styles.chip,
                          {
                            backgroundColor:
                              selectedEmotion === emotion
                                ? colors.accent.primary
                                : colors.background.base,
                          },
                        ]}
                        onPress={() => setSelectedEmotion(emotion)}
                      >
                        <ThemedText
                          size={12}
                          style={{
                            color:
                              selectedEmotion === emotion
                                ? colors.background.base
                                : colors.text.primary,
                          }}
                        >
                          {capitalize(emotion)}
                        </ThemedText>
                      </TouchableOpacity>
                    ))}
                  </View>

                  {/* Delta input: +/- toggle + unsigned numeric field */}
                  <View style={styles.inputRow}>
                    <ThemedText variant="secondary" size={13}>
                      Delta:
                    </ThemedText>
                    {/* Sign toggle */}
                    <TouchableOpacity
                      style={[
                        styles.signToggle,
                        { backgroundColor: colors.background.base, borderColor: colors.border.default },
                      ]}
                      onPress={() => {
                        const current = parseFloat(emotionDelta) || 0;
                        setEmotionDelta((-current).toFixed(1));
                      }}
                    >
                      <ThemedText size={16} style={{ color: colors.text.primary, fontWeight: '600' }}>
                        {(parseFloat(emotionDelta) || 0) >= 0 ? '+' : '−'}
                      </ThemedText>
                    </TouchableOpacity>
                    {/* Unsigned magnitude */}
                    <TextInput
                      style={[
                        styles.deltaInput,
                        {
                          backgroundColor: colors.background.base,
                          color: colors.text.primary,
                        },
                      ]}
                      value={Math.abs(parseFloat(emotionDelta) || 0).toFixed(1)}
                      onChangeText={(text) => {
                        // Strip any non-numeric except decimal point
                        const clean = text.replace(/[^0-9.]/g, '');
                        const num = parseFloat(clean) || 0;
                        const sign = (parseFloat(emotionDelta) || 0) < 0 ? -1 : 1;
                        setEmotionDelta((sign * num).toFixed(1));
                      }}
                      keyboardType="decimal-pad"
                      placeholder="0.0"
                      placeholderTextColor={colors.text.muted}
                    />
                    <ThemedText variant="muted" size={12}>(max ±5)</ThemedText>
                  </View>
                </View>
              )}
            </View>

            {/* Metabolism section */}
            <View style={styles.section}>
              <TouchableOpacity
                style={styles.toggleRow}
                onPress={() => setMetabolismEnabled(!metabolismEnabled)}
              >
                <View style={styles.toggleLeft}>
                  <Icon
                    name={metabolismEnabled ? 'checkbox-marked' : 'checkbox-blank-outline'}
                    size={22}
                    color={colors.accent.secondary}
                  />
                  <ThemedText style={styles.toggleLabel}>Metabolism</ThemedText>
                </View>
              </TouchableOpacity>

              {metabolismEnabled && (
                <View style={styles.toggleContent}>
                  {/* Type selector */}
                  <View style={styles.chipContainer}>
                    {(['eat', 'drink', 'sleep'] as const).map((type) => (
                      <TouchableOpacity
                        key={type}
                        style={[
                          styles.chip,
                          {
                            backgroundColor:
                              metabolismType === type
                                ? colors.accent.secondary
                                : colors.background.base,
                          },
                        ]}
                        onPress={() => setMetabolismType(type)}
                      >
                        <ThemedText
                          size={12}
                          style={{
                            color:
                              metabolismType === type
                                ? colors.background.base
                                : colors.text.primary,
                          }}
                        >
                          {capitalize(type)}
                        </ThemedText>
                      </TouchableOpacity>
                    ))}
                  </View>

                  {/* Item input */}
                  {metabolismType !== 'sleep' && (
                    <View style={styles.inputRow}>
                      <ThemedText variant="secondary" size={13}>
                        Item:
                      </ThemedText>
                      <TextInput
                        style={[
                          styles.itemInput,
                          {
                            backgroundColor: colors.background.base,
                            color: colors.text.primary,
                          },
                        ]}
                        value={metabolismItem}
                        onChangeText={setMetabolismItem}
                        placeholder={
                          metabolismType === 'eat' ? 'e.g., burger, pizza' : 'e.g., coffee, water'
                        }
                        placeholderTextColor={colors.text.muted}
                      />
                    </View>
                  )}
                </View>
              )}
            </View>

            {/* Substitution text section */}
            <View style={styles.section}>
              <View style={styles.substitutionHeader}>
                <ThemedText variant="secondary" size={12} style={styles.label}>
                  SUBSTITUTION TEXT
                </ThemedText>
                <TouchableOpacity onPress={handleAutoGenerate}>
                  <ThemedText size={12} style={{ color: colors.accent.primary }}>
                    Auto-generate
                  </ThemedText>
                </TouchableOpacity>
              </View>
              <TextInput
                style={[
                  styles.substitutionInput,
                  {
                    backgroundColor: colors.background.base,
                    color: colors.text.primary,
                  },
                ]}
                value={substitutionText}
                onChangeText={setSubstitutionText}
                placeholder="e.g., *eats a burger hungrily*"
                placeholderTextColor={colors.text.muted}
                multiline
                numberOfLines={3}
              />
            </View>
          </ScrollView>
          )}
        </ThemedView>
      </View>
    </Modal>
  );
};

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  container: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '90%',
  },
  containerExpanded: {
    // When the emoji picker is shown inline we need flex:1 so the child
    // inlinePickerContainer (flex:1) has something to expand into.
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  saveButton: {
    fontWeight: '600',
  },
  content: {
    padding: 16,
  },
  section: {
    marginBottom: 20,
  },
  label: {
    marginBottom: 8,
    fontWeight: '600',
  },
  emojiSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
  },
  errorText: {
    marginTop: 4,
    color: '#e53935',
  },
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  toggleLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  toggleLabel: {
    fontWeight: '500',
  },
  toggleContent: {
    marginTop: 12,
    marginLeft: 30,
  },
  chipContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  signToggle: {
    width: 36,
    height: 32,
    borderRadius: 6,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  deltaInput: {
    width: 70,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    fontSize: 14,
  },
  itemInput: {
    flex: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    fontSize: 14,
  },
  substitutionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  substitutionInput: {
    padding: 12,
    borderRadius: 8,
    minHeight: 80,
    textAlignVertical: 'top',
    fontSize: 14,
  },
  inlinePickerContainer: {
    flex: 1,
    minHeight: 300,
  },
  pickerToolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
});

export default EmojiActionEditModal;